---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: default-openstack-credential
  namespace: az-fixed-tenant
spec:
  encryptedData:
    clouds.yaml: AgBjnJloMJjQJFogTT9Wv2CI/KMObZZeFci9bsI339N72xWxYt/1SsjWe6cWp88/3fIa6LoRE2rV3241iOwjCQhz2fpdRGodehu02FkdvBLHJ6YGeYUL0c7pzKmrzl07idNA5vZ5C/Uw8EPXxmIATSSz+Lx3UOL+b9x7yoq4b5mhH/7SaYo04qNCRdRefut8ynDnuScptm6uiPAKjLmoGPK430XljJ34GCtpmGgDJn+JSTjNyritht1bsU+CtG8VBIfGorqMFGPjr4wDtxlre4Ukt2Ej2t3OgVykmJnlVP2G1ZQFJfyM+sxR5V2eMJvFa4caXGNJvVzW17QCZYV9jmZPxt9gggj/CUq4c8ArjV1/R1g9nhM0l+2oB9VYHaw3JPJtrNUiPkFNhvd1p9jp4oNfTktvfs7pwSm6xRZdWVMq06Nv0cuLJTcxk/+W3UASwpohzNCiGTxexmUQNtM7fJL+cnPTJJgSnOsFLffcGqGEvSexFQwTn56Bye0GMidx44oagQe5mibV4iCRre8kvnH9CL2SmvJuwnqe81LzegZV/cCwLwDSl0CWt0lhFShaC3O8IUVI2We5iznxEQSVLQn16pbTUxAsNaBTFfiDCAPFKMkytMzQFczGho6y8HD1C0cJ4v2+76NTzd9mpYFF9Ke7wWrpCSz1HTv/XGG8EL4vqYKu8hdyQA9IEXvRqzuNNgunP1vMQ69dbycEopGSgTPRbsgmmIumpHQIKikKaj3NKhE63QQzrdzxU0vldXMNHGR71h8j4nwXL5ZdD42S3Dd4GPnCLsACunAfMU+ZCU7iQoS1VWCSuXIeqeM4ihLRePNrCQJJ3hcIKu1dF0R19sLSpBiBWkGHDW9PPXnOo7WTejkn30RnOKkZbCAa6fWN20dBO6XR9CBd2USCnXR0CpWMTv17W+walSPWsnauwSRTmH9+s0p9lNK2zzuQQ36qkQ1kQdoYR0djVaCx4t0kDfYxMeiIWsFYnVjFnlTyWULgeF/e+YPXvmDLCqp5GzV8yxfJxAi5Q0IySRtCkj/ed9t9QXnazTiMqlblFajB+0no7dczR6U3cR4N75bqjd5GybZZSLlgsLja4wU81U/krxHo7wKFgkCO+a67MJ+4zpQLQUZxxXAW8EU7VEE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        credential.azimuth-cloud.io/provider: openstack
      name: default-openstack-credential
      namespace: az-fixed-tenant
