---
apiVersion: v1
kind: Secret
metadata:
  name: default-openstack-credential
  # This MUST match the namespace name in namespace.yaml
  namespace: az-example
  labels:
    # This label tells Azimuth that this secret contains a credential for the OpenStack provider
    credential.azimuth-cloud.io/provider: openstack
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
stringData:
  # Add the clouds.yaml for the application credential here
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: "<openstack auth URL>"
          application_credential_id: "<application credential ID>"
          application_credential_secret: "<application credential secret>"
        region_name: "<region name>"
        interface: "public"
        identity_api_version: 3
        auth_type: "v3applicationcredential"
