---
apiVersion: v1
kind: Secret
metadata:
  name: default-kubeconfig
  # This MUST match the namespace name in namespace.yaml
  namespace: az-example
  labels:
    # This label tells Azimuth to use this kubeconfig as the default kubeconfig
    apps.azimuth-cloud.io/default-kubeconfig: "true"
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
stringData:
  # Add the kubeconfig for the tenancy here
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: "<base64-encoded CA data>"
        server: "<API server URL>"
      name: example
    contexts:
    - context:
        cluster: example
        user: example-admin
      name: example-admin@example
    current-context: example-admin@example
    kind: Config
    preferences: {}
    users:
    - name: example-admin
      user:
        client-certificate-data: "<base64-encoded client certificate data>"
        client-key-data: "<base64-encoded key data>"
