---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: default-openstack-credential
  namespace: az-example
spec:
  encryptedData:
    clouds.yaml: AgB23jKm6TWe22eAtCc3T2g/uWc1FwF01Phe/YKlkrd7ZUrzhoaBuHjwbQ6EA3AaEiJDEArzQgwR0F5nExcSyDnDESYru+WEyuhhCEMnZuJMt2+ha/ynYL0mw281zW3ty6JeO4sd4kkb6Js36tzEOEgbJadH9sgv+oXCvZjlpKQ+NdjwdD3xFEsH6FDQDN/6dJUzaaHXjlXvES2aZhQfBaBqdbJjTrv2y7VDCmv9a3IVlG9uArh82F1AeRcX6nQLjA/PaCVGgbwjE2MEvIrDV4/r0sXz8kXVnQVxS/3XgdWS6uVPQjoHsbQqbtPpHHquLJcVFFS94GuQndZ+hlp0MbcesBbbB64ksv/vxUFEJb35Zy6zrrWOEYuOETI5TxD2kgAKSWfqCaGOUMlDkRGmpY9TChrGrN0VCexkZZU3qu+H/qQh9KQ2EEP+2w6FaizN743yGJJfdj6D95+cH9yE8/NEe9djLAoEEDrSky53Sto7sUWMhf2kijeduBGreq/LEtjIeLJ/dBs7XZAkk+tYoaylQ2g1T4V/HWI9b/d/TOI9DuB0oqHtHYdT92dyb0ugqnhsTOcXYQeik/AvWSARG7nm7sEQwjlwY0UJec44g5o1o8goitvRN7+5gvF6fC72nUU5W1pyEzmoivZoi/yj3DnQboNmzRQW+Rzcr8sAoetbE77kxlVjQzCC3Fw2xkjKTwWFdDDP2qrthUcG3gAOnKzeDpYLN8D9Zp2OMf3qC9Nra6uxioToy/Om8B5WhDWQnhVvY+LbLS0xZcgit7JUQxiCP7J/QeXVdaz4vVBQFJ/O8t+BBxHHN+c0KZMD+iG2pKl6l/NxGThUkcomza2W4Rhg9uOPdVJwU/Br8p3eAGwWXiBdnhv/TZV6pLfoUuD3IAdOgUNbxpOSSOpZEFxR0qtqxlnKg2pNSncjQunFOtupt7cbfi2YcU6DNbfx+MLMSNpHhMMMhxlRpDM9irx4yz3wTmzCmEfbmusEux5ApG3HQ9WURBIq4ynFrCxvcwb/GdcDaD4ceil6LQiPOGFBtxTM3Ql5gwNcJJWFjcJLMydTLhrRBuClAtuWRFLFz38hYqRHbgJwkDGJnLzslnIdSK/Jg1gr69vc6BTxZ01F5VVJ1cktrCApY68B3SA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        credential.azimuth-cloud.io/provider: openstack
      name: default-openstack-credential
      namespace: az-example
